---
# tasks file for openvpn

- include_tasks: create_certs_server.yaml

- include_tasks: create_openvpn_server.yaml

- include_tasks: create_sign_for_certs_server.yaml

- include_tasks: copy_certs_to_openvpn_server.yaml

- include_tasks: register_openvpn_clients.yaml

- include_tasks: create_sign_for_client_certs.yaml

- include_tasks: copy_certs_to_openvpn_client.yaml

- include_tasks: config_openvpn_server.yaml

- include_tasks: create_ovpn_infra.yaml

- include_tasks: create_ovpn_client.yaml

