---
dependency:
  name: galaxy

driver:
  name: vagrant
  provider:
    name: libvirt
  cachier: machine
  parallel: true
  default_box: 'ubuntu/focal64'

platforms:
  - name: localhost
    interfaces:
      - network_name: forwarded_port
        guest: 8080
        host: 8080
    config_options:
      ssh.keep_alive: yes
      ssh.remote_user: 'vagrant'
      synced_folder: true
    box: 'ubuntu/focal64'
    memory: 512
    cpus: 1

provisioner:
  name: ansible
  inventory:
    host_vars:
      localhost: 
        ansible_ssh_host: 127.0.0.1 
        ansible_ssh_port: 2222 
        ansible_ssh_user: vagrant 
        ansible_ssh_private_key_file: /cygdrive/c/Users/ivano/vagrant-test/.vagrant/machines/default/virtualbox/private_key

scenario:
  test_sequence:
    - destroy
    - create
    - converge
    - verify